name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Mysql Docker image
      run: |
        docker run --name some-mysql -e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:8
        
    - name: Install python module
      run: |
        pip install -e .
        
    - name: Run sqlite migrate command line
      run: |
        dbmt -d sql-tests/mysql clean
        dbmt -d sql-tests/mysql migrate
