name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      mysqldb:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3


    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Verify MariaDB connection
    #   run: |
    #     while ! mysqladmin ping -h"127.0.0.1" -P"3306" -u root -ppassword --silent; do
    #       sleep 1
    #     done   

    - name: Install python module
      run: |
        pip install -e .
        
    - name: Run sqlite migrate command line
      run: |
        dbmt -d sql-tests/mysql clean
        dbmt -d sql-tests/mysql migrate
